services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: . 
    container_name: nest-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:        
      - DATABASE_URL=${DATABASE_URL}  
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:dev"

volumes:
  postgres_data:
